version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - ./test_db:/var/lib/postgresql/data
  web:
    build: django_training_platform/.
    command: >
      sh -c "ls &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
    - ./django_training_platform/:/web
    ports:
      - "8000:8000"
    depends_on:
      - db
