version: "3.9"

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db_mysql_test:/var/lib/mysql
  web:
    build: django_training_platform/.
    command: >
      sh -c "ls &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
    - ./django_training_platform/:/web
    env_file:
      - web_variables.env
    ports:
      - "8000:8000"
    depends_on:
      - db
