# Generated by Django 3.1.4 on 2021-02-09 12:42

from django.db import migrations
# from django.apps import apps


class Migration(migrations.Migration):

    dependencies = [
        ('training_platform', '0003_auto_20210209_1234'),
    ]

    def set_my_defaults(self, apps, schema_editor):
        app_config = apps.get_app_config('training_platform')
        models_to_change = ['Comment', 'Grade', 'CompletedTask', 'Task']
        for model_to_change in models_to_change:
            model = app_config.get_model(model_to_change)
            for model_record in model.objects.all().iterator():
                model_record.cource = model_record.
        Series = AppConfig.get_model('Series')
        for series in Series.objects.all().iterator():
            series.updated_as = datetime.now() + timedelta(days=series.some_other_field)
            series.save()

    operations = [
    ]
