# Generated by Django 3.1.4 on 2021-02-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_platform', '0004_auto_20210209_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='training_platform.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='training_platform.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='training_platform.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='training_platform.course'),
            preserve_default=False,
        ),
    ]
